In [1]:
1+1

2

In [3]:
import numpy

In [4]:
numpy.mean([1,2,3,4])

np.float64(2.5)

In [19]:
a = [1,2,3]

In [20]:
b = [2,3,4]

In [21]:
c = []

In [23]:
for i in a:
    for j in b:
        if a.index(i)==b.index(j):
            c.append(i+j)
        

In [24]:
print(c)

[3, 5, 7]


In [8]:
a+b

[1, 2, 3, 2, 3, 4]

In [9]:
import numpy as np

In [25]:
a = np.array([1,2,3])

In [26]:
b = np.array([2,3,4])

In [12]:
a+b

array([3, 5, 7])

In [13]:
a.size

3

In [27]:
np.dot(a,b)

np.int64(20)

In [30]:
x = np.array([[1, 2, 3, 4],[4, 5,6, 8]])

In [31]:
x

array([[1, 2, 3, 4],
       [4, 5, 6, 8]])

In [32]:
x.shape

(2, 4)

In [38]:
x.size

8

In [39]:
x.dtype

dtype('int64')

In [33]:
arr1 = np.array([1, 2, 3, 4])

In [34]:
arr1

array([1, 2, 3, 4])

In [35]:
arr1.shape

(4,)

In [36]:
arr1.size

4

In [40]:
x

array([[1, 2, 3, 4],
       [4, 5, 6, 8]])

In [41]:
x.shape

(2, 4)

In [42]:
x.size

8

In [44]:
x.dtype

dtype('int64')

In [45]:
x[0]

array([1, 2, 3, 4])

In [46]:
x[1]

array([4, 5, 6, 8])

In [47]:
x[0,0]

np.int64(1)

In [48]:
x[0,3]

np.int64(4)

In [49]:
x[1,3]

np.int64(8)

In [50]:
x[1,2:4]

array([6, 8])

In [51]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [52]:
a+b

array([5, 7, 9])

In [53]:
a-b

array([-3, -3, -3])

In [54]:
np.dot(a,b)

np.int64(32)

In [55]:
data = np.array([1, 2, 3, 4, 5, 6])


In [56]:
data

array([1, 2, 3, 4, 5, 6])

In [57]:
np.mean(data)

np.float64(3.5)

In [58]:
np.std(data)

np.float64(1.707825127659933)

In [59]:
np.median(data)

np.float64(3.5)

In [60]:
np.sum(data)

np.int64(21)

In [61]:
x

array([[1, 2, 3, 4],
       [4, 5, 6, 8]])

In [62]:
x.shape

(2, 4)

In [63]:
x.reshape(4,2)

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 8]])

In [65]:
x.flatten()

array([1, 2, 3, 4, 4, 5, 6, 8])

In [67]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [68]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [69]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [70]:
np.ones((6, 3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
np.random.rand(2,3)

array([[0.12438451, 0.68488802, 0.57741318],
       [0.63912691, 0.95405327, 0.85566966]])

In [72]:
!pip install beautifulsoup4

You should consider upgrading via the 'C:\Users\Dinesh\Documents\Data_Analytics\myenv\Scripts\python.exe -m pip install --upgrade pip' command.


In [73]:
from bs4 import BeautifulSoup

In [74]:
url = "https://medium.com/@abidshafee/introduction-to-python-programming-a-beginners-guide-d9658a554d8d"

In [75]:
import requests

In [76]:
response = requests.get(url)

In [78]:
response.text

'<!doctype html><html lang="en"><head><title data-rh="true">Introduction to Python Programming: A Beginner’s Guide | by Shafekul Abid | Medium</title><meta data-rh="true" charset="utf-8"/><meta data-rh="true" name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1,maximum-scale=1"/><meta data-rh="true" name="theme-color" content="#000000"/><meta data-rh="true" name="twitter:app:name:iphone" content="Medium"/><meta data-rh="true" name="twitter:app:id:iphone" content="828256236"/><meta data-rh="true" property="al:ios:app_name" content="Medium"/><meta data-rh="true" property="al:ios:app_store_id" content="828256236"/><meta data-rh="true" property="al:android:package" content="com.medium.reader"/><meta data-rh="true" property="fb:app_id" content="542599432471018"/><meta data-rh="true" property="og:site_name" content="Medium"/><meta data-rh="true" property="og:type" content="article"/><meta data-rh="true" property="article:published_time" content="2023-10-07T07:02:46.920

In [80]:
web = BeautifulSoup(response.text, 'html.parser')

In [83]:
web.title.text

'Introduction to Python Programming: A Beginner’s Guide | by Shafekul Abid | Medium'

In [84]:
web.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <title data-rh="true">\n   Introduction to Python Programming: A Beginner’s Guide | by Shafekul Abid | Medium\n  </title>\n  <meta charset="utf-8" data-rh="true"/>\n  <meta content="width=device-width,minimum-scale=1,initial-scale=1,maximum-scale=1" data-rh="true" name="viewport"/>\n  <meta content="#000000" data-rh="true" name="theme-color"/>\n  <meta content="Medium" data-rh="true" name="twitter:app:name:iphone"/>\n  <meta content="828256236" data-rh="true" name="twitter:app:id:iphone"/>\n  <meta content="Medium" data-rh="true" property="al:ios:app_name"/>\n  <meta content="828256236" data-rh="true" property="al:ios:app_store_id"/>\n  <meta content="com.medium.reader" data-rh="true" property="al:android:package"/>\n  <meta content="542599432471018" data-rh="true" property="fb:app_id"/>\n  <meta content="Medium" data-rh="true" property="og:site_name"/>\n  <meta content="article" data-rh="true" property="og:type"/>\n  <meta content="2023-1

In [85]:
for p in web.find_all('p'):
    print(p.text)

Sign up
Sign in
Sign up
Sign in
Shafekul Abid
Follow
--
Listen
Share
1. Introduction to Python Programming
2. Getting Started with Python
3. Python Basics
4. Control Flow
5. Data Structures in Python
6. Functions and Modules
7. Object-Oriented Programming (OOP)
8. Exception Handling
9. File Handling
10. Introduction to Libraries and Frameworks
11. Conclusion
12. Where You Should Go Next
Python, renowned for its simplicity and readability, stands as one of the most versatile and widely adopted programming languages in the world today. Created by Guido van Rossum in the late 1980s, Python was designed with a focus on code readability, enabling developers to express concepts in fewer lines of code compared to languages like C++ or Java.
The importance of Python transcends traditional coding realms. Its versatility allows it to be employed in a multitude of applications, ranging from web development and scientific computing to data analysis, artificial intelligence, and more. Python's exte