# NumPy Basics for Data Analytics Beginners

**NumPy** (Numerical Python) is a fundamental package for scientific computing in Python. It is especially useful for data analysis, machine learning, and large-scale numerical computations.


## 1. Importing NumPy
We usually import NumPy using the alias `np`.

In [ ]:
import numpy as np

## 2. Creating Arrays
NumPy arrays are more efficient than Python lists for numerical operations.

In [ ]:
arr1 = np.array([1, 2, 3, 4])
print("1D Array:", arr1)

arr2 = np.array([[1, 2], [3, 4]])
print("2D Array:\n", arr2)

## 3. Array Attributes
Attributes like shape, size, and datatype give insights into the array structure.

In [ ]:
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data Type:", arr2.dtype)

## 4. Indexing and Slicing
Accessing elements or subarrays using indexing and slicing.

In [ ]:
print("Element at (0,1):", arr2[0,1])
print("First row:", arr2[0])
print("First column:", arr2[:,0])

## 5. Basic Operations
NumPy supports element-wise operations and matrix operations.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)
print("Multiplication:", a * b)
print("Dot Product:", np.dot(a, b))

## 6. Useful NumPy Functions
NumPy provides many built-in functions useful for analytics.

In [ ]:
data = np.array([1, 2, 3, 4, 5, 6])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Sum:", np.sum(data))

## 7. Reshaping and Flattening
Convert arrays to different shapes using reshape and flatten.

In [ ]:
reshaped = arr2.reshape(4, 1)
print("Reshaped Array:\n", reshaped)

flattened = arr2.flatten()
print("Flattened Array:", flattened)

## 8. Generating Arrays
Quickly generate arrays with zeros, ones, or random values.

In [ ]:
print("Zeros:", np.zeros((2, 2)))
print("Ones:", np.ones((2, 3)))
print("Random:", np.random.rand(2, 2))

In [2]:
import numpy as np

arr = np.random.rand(4, 4) * (50 - 10) + 10
print(arr)

[[40.38929519 31.28298098 47.5308911  11.05176489]
 [38.47778367 48.14428539 47.17419563 12.68322909]
 [11.3967383  34.07457116 22.87034698 22.50057223]
 [25.97490838 31.78888413 43.90795367 31.15891282]]
